In [20]:
import torch
import torch_directml as dml
import numpy as np

Tensors can be created directly from data:

In [3]:


data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

Tensors can be created from numpy arrays and vice versa:

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

You can also create a tenser based on another tensor, resulting in the same shape:

In [5]:
x_ones = torch.ones_like(x_data)
print(f"Ones tensor: \n {x_ones}")
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random tensor: \n {x_rand}")

Ones tensor: 
 tensor([[1, 1],
        [1, 1]])
Random tensor: 
 tensor([[0.6241, 0.1263],
        [0.2534, 0.7324]])


You can also create tensors from a shape:

In [6]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random tensor: \n {rand_tensor}")
print(f"Ones tensor: \n {ones_tensor}")
print(f"Zeroes tensor: \n {zeros_tensor}")

Random tensor: 
 tensor([[0.2242, 0.0662, 0.2144],
        [0.6222, 0.1389, 0.9044]])
Ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeroes tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


Tensor attribute
Tensor attributes describe their shape, datatype, and the device on which they are stored. 


In [7]:
tensor = torch.rand(5, 5)

print(tensor)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[0.6125, 0.5443, 0.6869, 0.0345, 0.4593],
        [0.0123, 0.3976, 0.3526, 0.3281, 0.1637],
        [0.3090, 0.7534, 0.1127, 0.9669, 0.2918],
        [0.6423, 0.6696, 0.9388, 0.5034, 0.4191],
        [0.6763, 0.9091, 0.2112, 0.7167, 0.6113]])
Shape of tensor: torch.Size([5, 5])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Tensor Operations
Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, etc.), sampling and more are
available. You can find the full list here. https://pytorch.org/docs/stable/torch.html

Each of them can be run on the GPU

In [21]:
d = dml.device()
print(d)
tensor = tensor.to(d)
print(f"Tensor is stored on: {tensor.device}")


print("DML device count:", dml.device_count())
# Try to print adapter names if your build exposes it:
for i in range(dml.device_count()):
    try:
        print(f"{i}: {dml.device_name(i)}")
    except Exception:
        print(f"{i}: (name API not available in this build)")

# IF the pc has a Nvidia GPU:
# if torch.cuda.is_available():
#     tensor = tensor.to('cuda')
#     print(f"Tensor is stored on: {tensor.device}")

privateuseone:0
Tensor is stored on: privateuseone:0
DML device count: 1
0: Intel(R) Iris(R) Xe Graphics


In [43]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [41]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

t2 = torch.stack([tensor, tensor, tensor], dim=0)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


In [ ]:
# Tensor multiplication: Element-wise product
print(rand_tensor.mul(rand_tensor))
print(rand_tensor*rand_tensor)

tensor([[0.0502, 0.0044, 0.0460],
        [0.3871, 0.0193, 0.8180]])
tensor([[0.0502, 0.0044, 0.0460],
        [0.3871, 0.0193, 0.8180]])


In [50]:
# Tensor matrix multiplication:
print(rand_tensor.matmul(rand_tensor.T))
print(rand_tensor @ rand_tensor.T)
print(tensor.matmul(tensor.T))

tensor([[0.1006, 0.3426],
        [0.3426, 1.2244]])
tensor([[0.1006, 0.3426],
        [0.3426, 1.2244]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
