In [2]:
import torch

In [6]:
#Prepopulate a tensor with evenly spaced values starting at 0, 12 not included
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [7]:
#inspect how many elements are in a tensor
x.numel()

12

In [ ]:
#Find the shape of a tensor:
x.shape
#OBS since this is a vetor we get the size returned

torch.Size([12])

In [11]:
#We can change the shape of a tensor without altering its size or values
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
#Notice that the elements of our vector are laid out one row at a time and thus x[3] == X[0, 3]
print(x[3], X[0,3])

tensor(3.) tensor(3.)


Note that specifying every shape component to reshape is redundant. Because we already know our tensor’s size, we can work out one component of the shape given the rest. For example, given a tensor of size n and target shape ( h, w), we know that w = n / h.

To automatically infer one component of the shape, we can place a -1 for the shape component that should be inferred automatically. In our case, instead of calling x.reshape(3, 4), we could have equivalently called x.reshape(-1, 4) or x.reshape(3, -1).

In [13]:
Y = x.reshape(-1, 4)
Y

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

its also possible to make standard tensors

In [19]:
# 2 Dimensional tensor: 2 blocks, 3 rows, 4 columns
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [20]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
torch.rand((2, 3, 4))
# use randn for normal (gaussian distribution)
# use rand for uniform distribution
# other distributions:

# torch.bernoulli(torch.full((2, 3, 4), 0.7))  # Probability of 1 is 0.7
# torch.poisson(torch.full((2, 3, 4), 2.0))  # Lambda=2.0
# exp = torch.distributions.Exponential(rate=1.0)
# exp.sample((2, 3, 4))

tensor([[[0.7985, 0.0702, 0.1634, 0.7648],
         [0.8010, 0.8347, 0.2128, 0.8033],
         [0.8026, 0.2760, 0.6324, 0.5565]],

        [[0.1171, 0.6661, 0.6897, 0.4213],
         [0.2392, 0.1888, 0.0683, 0.7039],
         [0.9754, 0.1991, 0.8703, 0.6499]]])

In [ ]:
torch.rand_like(Y)
# takes the same shape as previous tensor

tensor([[0.5772, 0.6667, 0.2986, 0.0406],
        [0.9311, 0.4399, 0.1572, 0.0197],
        [0.3677, 0.7049, 0.7674, 0.8278]])

In [26]:
# Tensors can also be generated using fixed values:
torch.tensor([[2, 3, 3], [1, 1, 1], [3, 4, 5]])

tensor([[2, 3, 3],
        [1, 1, 1],
        [3, 4, 5]])

# Indexing and slicing
